//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_program::{ pubkey, pubkey::Pubkey };

/// `blueshift_secp256r1_vault` program ID.
pub const BLUESHIFT_SECP256R1_VAULT_ID: Pubkey = pubkey!(
    "HNUZnoUCPVg8NarCwoXsLRZEyvaZnp34DvYz4aSJTdHt"
);
