//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#deposit;
  pub(crate) mod r#withdraw;

  pub use self::r#deposit::*;
  pub use self::r#withdraw::*;

